# Generated by Django 2.2.7 on 2019-11-27 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='slug',
        ),
    ]
