# Generated by Django 2.2.7 on 2019-11-27 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0005_auto_20191127_1552'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=255)),
                ('contrasena', models.CharField(max_length=255)),
                ('correo', models.CharField(max_length=255)),
                ('nombre_completo', models.CharField(max_length=255)),
                ('imagen_perfil', models.ImageField(blank=True, null=True, upload_to='static/images/perfil')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
